#!/bin/bash
set -e

help() {
	cat <<EOF
		Usage: gh copr
		Display an list of open PRs. Select PR to open in the browser.
		Options:
			--help show this message
		Dependencies: fzf
EOF
}

if ! git rev-parse --git-dir > /dev/null 2>&1; then
	echo "not a git repository"
	exit 1 
fi

# Make sure fzf is available
if ! type -p fzf >/dev/null; then
	echo "fzf not found on the system, try:" 
	echo "brew install fzf"
	>&2
	exit 1
fi

pull_requests_that_need_my_review() {
	template='{{range(pluck "node" .data.search.edges) -}}
	{{tablerow .title (.author.login | autocolor "cyan") (.url | autocolor "blue") -}}
	{{end -}}
	{{tablerender}}'

	query='query {
		search(query: "is:open is:pr review-requested:@me", type: ISSUE, first: 100) {
			edges {
				node {
					... on PullRequest {
						title
						author {
							login
							... on User {
								name
							}
						}
						url
					}
				}
			}
		}
	}'

	GH_FORCE_TTY=100% gh api graphql --paginate -f query="$query" -t "$template"
}

while test $# != 0; do
	case "$1" in
		--help|-h)
			help
			exit
			;;
		*)
			if [ -n "$VAR" ]; then
				help >&2
				exit 1
			fi
	esac
	shift
done

selected=$(fzf --ansi <<<"$(pull_requests_that_need_my_review)")
[ -n "$selected" ] || exit 1
gh pr view --web "${selected##* }"
